package com.clocial.walkdab.app.enums.semantic

object CommonMeanings {
    const val accountNumber = "accountNumber"
    const val agent = "agent"
    const val bookingCode = "bookingCode"
    const val coordinates = "coordinates"
    const val addressLine1 = "addressLine1"
    const val addressLine2 = "addressLine2"
    const val addressLine3 = "addressLine3"
    const val addressLine4 = "addressLine4"
    const val birthDate = "birthDate"
    const val cityName = "cityName"
    const val clientName = "clientName"
    const val clientRef = "clientRef"
    const val companyName = "companyName"
    const val contractNumber = "contractNumber"
    const val countryCode = "countryCode"
    const val countryName = "countryName"
    const val countyName = "countyName"
    const val createdBy = "createdBy"
    const val createdOn = "createdOn"
    const val dueDate = "dueDate"
    const val email = "email"
    const val endDate = "endDate"
    const val firstName = "firstName"
    const val issueDate = "issueDate"
    const val lastName = "lastName"
    const val middleInitial = "middleInitial"
    const val middleName = "middleName"
    const val orderNumber = "orderNumber"
    const val password = "password"
    const val phoneNumber = "phoneNumber"
    const val plateNumber = "plateNumber"
    const val postCode = "postCode"
    const val reference = "reference"
    const val regionName = "regionName"
    const val secret = "secret"
    const val startDate = "startDate"
    const val timeZone = "timeZone"
    const val updatedBy = "updatedBy"
    const val updatedOn = "updatedOn"
    const val url = "url"
    const val userName = "userName"
    const val vatNumber = "vatNumber"
}